# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f193b52fcb830700a644e734aecc1d72ab3d1d1dd73e9ac2062ae009d0abfe7f5c6a2d5265183165e61b51076930a5c9bb28d3c2a19ab8c874dd29decef65589

test:
  secret_key_base: df63e8109c88241b075be5cade304ad80631a4f340c77780157825f0c09b3a0ae26469bc43ddf77eed559e5d1153599dc3355c4eff7e9eede85651fca909f1ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
